# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'choice.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(638, 137)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/user-add-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QFrame{\n"
                           "    border: None;\n"
                           "}")
        self.grd_lay_mainest = QtWidgets.QGridLayout(Form)
        self.grd_lay_mainest.setObjectName("grd_lay_mainest")
        self.frame_main = QtWidgets.QFrame(Form)
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.grd_lay_main = QtWidgets.QGridLayout(self.frame_main)
        self.grd_lay_main.setObjectName("grd_lay_main")
        self.frame_single = QtWidgets.QFrame(self.frame_main)
        self.frame_single.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_single.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_single.setObjectName("frame_single")
        self.v_lay_single = QtWidgets.QVBoxLayout(self.frame_single)
        self.v_lay_single.setObjectName("v_lay_single")
        self.btn_single = QtWidgets.QPushButton(self.frame_single)
        self.btn_single.setStyleSheet("QPushButton:hover:pressed{\n"
                                      "    background-color: rgb(203, 203, 203);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    background-color: rgb(220, 220, 220);\n"
                                      "}\n"
                                      "QPushButton{\n"
                                      "    background-color: rgb(235, 235, 235);\n"
                                      "    padding: 5;\n"
                                      "    border-radius: 22;\n"
                                      "    border: 1px solid rgb(86, 86, 86);}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/User & Faces/user-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_single.setIcon(icon1)
        self.btn_single.setIconSize(QtCore.QSize(32, 32))
        self.btn_single.setObjectName("btn_single")
        self.v_lay_single.addWidget(self.btn_single)
        self.grd_lay_main.addWidget(self.frame_single, 1, 0, 1, 1)
        self.lbl_type_of_visit = QtWidgets.QLabel(self.frame_main)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_type_of_visit.setFont(font)
        self.lbl_type_of_visit.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_type_of_visit.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_type_of_visit.setObjectName("lbl_type_of_visit")
        self.grd_lay_main.addWidget(self.lbl_type_of_visit, 0, 0, 1, 2)
        self.frame_gorup = QtWidgets.QFrame(self.frame_main)
        self.frame_gorup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_gorup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_gorup.setObjectName("frame_gorup")
        self.v_lay_group = QtWidgets.QVBoxLayout(self.frame_gorup)
        self.v_lay_group.setObjectName("v_lay_group")
        self.btn_group = QtWidgets.QPushButton(self.frame_gorup)
        self.btn_group.setStyleSheet("QPushButton:hover:pressed{\n"
                                     "    background-color: rgb(203, 203, 203);\n"
                                     "}\n"
                                     "QPushButton:hover{\n"
                                     "    background-color: rgb(220, 220, 220);\n"
                                     "}\n"
                                     "QPushButton{\n"
                                     "    background-color: rgb(235, 235, 235);\n"
                                     "    padding: 5;\n"
                                     "    border-radius: 22;\n"
                                     "    border: 1px solid rgb(255, 170, 0);}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/User & Faces/group-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_group.setIcon(icon2)
        self.btn_group.setIconSize(QtCore.QSize(32, 32))
        self.btn_group.setObjectName("btn_group")
        self.v_lay_group.addWidget(self.btn_group)
        self.grd_lay_main.addWidget(self.frame_gorup, 1, 1, 1, 1)
        self.grd_lay_mainest.addWidget(self.frame_main, 0, 0, 1, 1, QtCore.Qt.AlignVCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Выберите тип посещения"))
        self.btn_single.setText(_translate("Form", "Личное посещение"))
        self.lbl_type_of_visit.setText(_translate("Form", "Выберите тип посещения:"))
        self.btn_group.setText(_translate("Form", "Групповое посещение"))
