# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(533, 210)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("padding: 5;\n"
"background-color: rgb(255, 170, 0);\n"
"border: None;\n"
"border-radius: 12;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_3)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.le_email = QtWidgets.QLineEdit(self.frame)
        self.le_email.setObjectName("le_email")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_email)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.le_password = QtWidgets.QLineEdit(self.frame)
        self.le_password.setObjectName("le_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_password)
        self.le_rep_pas = QtWidgets.QLineEdit(self.frame)
        self.le_rep_pas.setObjectName("le_rep_pas")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_rep_pas)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.verticalLayout.addWidget(self.frame)
        self.pb_reg = QtWidgets.QPushButton(Form)
        self.pb_reg.setObjectName("pb_reg")
        self.verticalLayout.addWidget(self.pb_reg)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Авторизация"))
        self.label.setText(_translate("Form", "Почта"))
        self.label_2.setText(_translate("Form", "Пароль"))
        self.label_4.setText(_translate("Form", "Повторите пароль"))
        self.pb_reg.setText(_translate("Form", "Зарегестрироваться"))
