# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'single.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1062, 580)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        Form.setFont(font)
        Form.setStyleSheet("font: 25 11pt \"Roboto\";\n"
                           "")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setStyleSheet("QFrame{\n"
                                    "    border: None;\n"
                                    "    border-radius: 20;\n"
                                    "}\n"
                                    "QLineEdit{\n"
                                    "    padding: 2\n"
                                    "}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_20 = QtWidgets.QLabel(self.frame_10)
        self.label_20.setStyleSheet("border: None;\n"
                                    "border-radius:10;\n"
                                    "background-color: rgb(255, 170, 0);\n"
                                    "padding: 5;")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 0, 0, 1, 1)
        self.lbl_dep = QtWidgets.QLabel(self.frame_10)
        self.lbl_dep.setObjectName("lbl_dep")
        self.gridLayout_8.addWidget(self.lbl_dep, 1, 0, 1, 1)
        self.le_dep = QtWidgets.QLineEdit(self.frame_10)
        self.le_dep.setObjectName("le_dep")
        self.gridLayout_8.addWidget(self.le_dep, 2, 0, 1, 1)
        self.lbl_sfl = QtWidgets.QLabel(self.frame_10)
        self.lbl_sfl.setObjectName("lbl_sfl")
        self.gridLayout_8.addWidget(self.lbl_sfl, 3, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_8.addWidget(self.lineEdit_12, 4, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_10, 0, 2, 1, 1, QtCore.Qt.AlignVCenter)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setStyleSheet("QFrame{\n"
                                   "    border: None;\n"
                                   "    border-radius: 20;\n"
                                   "}\n"
                                   "QLineEdit, QDateEdit{\n"
                                   "    padding: 2;\n"
                                   "}\n"
                                   "")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_15 = QtWidgets.QLabel(self.frame_9)
        self.label_15.setStyleSheet("border: None;\n"
                                    "border-radius:10;\n"
                                    "background-color: rgb(255, 170, 0);\n"
                                    "padding: 5;")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_9)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_17 = QtWidgets.QLabel(self.frame_9)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.de_start = QtWidgets.QDateEdit(self.frame_9)
        self.de_start.setWrapping(True)
        self.de_start.setFrame(False)
        self.de_start.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.de_start.setAccelerated(False)
        self.de_start.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.de_start.setProperty("showGroupSeparator", False)
        self.de_start.setCalendarPopup(True)
        self.de_start.setObjectName("de_start")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.de_start)
        self.horizontalLayout_4.addLayout(self.formLayout_4)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_18 = QtWidgets.QLabel(self.frame_9)
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.de_end = QtWidgets.QDateEdit(self.frame_9)
        self.de_end.setCalendarPopup(True)
        self.de_end.setObjectName("de_end")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.de_end)
        self.horizontalLayout_4.addLayout(self.formLayout_5)
        self.gridLayout_7.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.lbl_target = QtWidgets.QLabel(self.frame_9)
        self.lbl_target.setObjectName("lbl_target")
        self.gridLayout_7.addWidget(self.lbl_target, 3, 0, 1, 1)
        self.le_target = QtWidgets.QLineEdit(self.frame_9)
        self.le_target.setObjectName("le_target")
        self.gridLayout_7.addWidget(self.le_target, 4, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_9, 0, 1, 1, 1, QtCore.Qt.AlignVCenter)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_1 = QtWidgets.QFrame(self.frame_2)
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_1)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_last = QtWidgets.QLabel(self.frame_1)
        self.lbl_last.setObjectName("lbl_last")
        self.gridLayout_3.addWidget(self.lbl_last, 2, 0, 1, 1)
        self.le_last = QtWidgets.QLineEdit(self.frame_1)
        self.le_last.setObjectName("le_last")
        self.gridLayout_3.addWidget(self.le_last, 2, 1, 1, 1)
        self.le_email = QtWidgets.QLineEdit(self.frame_1)
        self.le_email.setObjectName("le_email")
        self.gridLayout_3.addWidget(self.le_email, 4, 1, 1, 1)
        self.lbl_sur = QtWidgets.QLabel(self.frame_1)
        self.lbl_sur.setObjectName("lbl_sur")
        self.gridLayout_3.addWidget(self.lbl_sur, 0, 0, 1, 1)
        self.le_name = QtWidgets.QLineEdit(self.frame_1)
        self.le_name.setObjectName("le_name")
        self.gridLayout_3.addWidget(self.le_name, 1, 1, 1, 1)
        self.lbl_email = QtWidgets.QLabel(self.frame_1)
        self.lbl_email.setObjectName("lbl_email")
        self.gridLayout_3.addWidget(self.lbl_email, 4, 0, 1, 1)
        self.le_phone = QtWidgets.QLineEdit(self.frame_1)
        self.le_phone.setInputMask("")
        self.le_phone.setMaxLength(12)
        self.le_phone.setFrame(True)
        self.le_phone.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.le_phone.setClearButtonEnabled(False)
        self.le_phone.setObjectName("le_phone")
        self.gridLayout_3.addWidget(self.le_phone, 3, 1, 1, 1)
        self.le_sur = QtWidgets.QLineEdit(self.frame_1)
        self.le_sur.setObjectName("le_sur")
        self.gridLayout_3.addWidget(self.le_sur, 0, 1, 1, 1)
        self.lbl_phone = QtWidgets.QLabel(self.frame_1)
        self.lbl_phone.setObjectName("lbl_phone")
        self.gridLayout_3.addWidget(self.lbl_phone, 3, 0, 1, 1)
        self.lbl_name = QtWidgets.QLabel(self.frame_1)
        self.lbl_name.setObjectName("lbl_name")
        self.gridLayout_3.addWidget(self.lbl_name, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_1, 1, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_photo = QtWidgets.QLabel(self.frame_8)
        self.lbl_photo.setMaximumSize(QtCore.QSize(230, 200))
        self.lbl_photo.setStyleSheet("")
        self.lbl_photo.setText("")
        self.lbl_photo.setPixmap(QtGui.QPixmap("import/User.jpg"))
        self.lbl_photo.setScaledContents(True)
        self.lbl_photo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_photo.setObjectName("lbl_photo")
        self.verticalLayout.addWidget(self.lbl_photo)
        self.pb_photo = QtWidgets.QPushButton(self.frame_8)
        self.pb_photo.setStyleSheet("QPushButton:hover:pressed{\n"
                                    "    background-color: rgb(203, 203, 203);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(220, 220, 220);\n"
                                    "}\n"
                                    "QPushButton{\n"
                                    "    background-color: rgb(235, 235, 235);\n"
                                    "    padding: 5;\n"
                                    "    border-radius: 12;\n"
                                    "    border: 1px solid rgb(255, 170, 0);}")
        self.pb_photo.setObjectName("pb_photo")
        self.verticalLayout.addWidget(self.pb_photo)
        self.gridLayout_5.addWidget(self.frame_8, 1, 3, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_num = QtWidgets.QLabel(self.frame_6)
        self.lbl_num.setObjectName("lbl_num")
        self.gridLayout_4.addWidget(self.lbl_num, 4, 0, 1, 1)
        self.lbl_birth = QtWidgets.QLabel(self.frame_6)
        self.lbl_birth.setObjectName("lbl_birth")
        self.gridLayout_4.addWidget(self.lbl_birth, 2, 0, 1, 1)
        self.lbl_org = QtWidgets.QLabel(self.frame_6)
        self.lbl_org.setObjectName("lbl_org")
        self.gridLayout_4.addWidget(self.lbl_org, 0, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_4.addWidget(self.lineEdit_6, 0, 1, 1, 1)
        self.le_num = QtWidgets.QLineEdit(self.frame_6)
        self.le_num.setObjectName("le_num")
        self.gridLayout_4.addWidget(self.le_num, 4, 1, 1, 1)
        self.le_series = QtWidgets.QLineEdit(self.frame_6)
        self.le_series.setObjectName("le_series")
        self.gridLayout_4.addWidget(self.le_series, 3, 1, 1, 1)
        self.lbl_prim = QtWidgets.QLabel(self.frame_6)
        self.lbl_prim.setObjectName("lbl_prim")
        self.gridLayout_4.addWidget(self.lbl_prim, 1, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_4.addWidget(self.lineEdit_7, 1, 1, 1, 1)
        self.lbl_series = QtWidgets.QLabel(self.frame_6)
        self.lbl_series.setObjectName("lbl_series")
        self.gridLayout_4.addWidget(self.lbl_series, 3, 0, 1, 1)
        self.de_birth = QtWidgets.QDateEdit(self.frame_6)
        self.de_birth.setAlignment(QtCore.Qt.AlignCenter)
        self.de_birth.setCalendarPopup(True)
        self.de_birth.setObjectName("de_birth")
        self.gridLayout_4.addWidget(self.de_birth, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_6, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setStyleSheet("border: None;\n"
                                    "border-radius:12;\n"
                                    "background-color: rgb(255, 170, 0);\n"
                                    "padding: 7;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 4)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setStyleSheet("border: None;\n"
                                 "border-radius:12;\n"
                                 "background-color: rgb(255, 170, 0);\n"
                                 "padding: 7;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.pb_upload = QtWidgets.QPushButton(self.frame_4)
        self.pb_upload.setStyleSheet("QPushButton:hover:pressed{\n"
                                     "    background-color: rgb(203, 203, 203);\n"
                                     "}\n"
                                     "QPushButton:hover{\n"
                                     "    background-color: rgb(220, 220, 220);\n"
                                     "}\n"
                                     "QPushButton{\n"
                                     "    background-color: rgb(235, 235, 235);\n"
                                     "    padding: 5;\n"
                                     "    border-radius: 12;\n"
                                     "    border: 1px solid rgb(86, 86, 86);}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/System/upload-2-fill.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_upload.setIcon(icon)
        self.pb_upload.setObjectName("pb_upload")
        self.verticalLayout_2.addWidget(self.pb_upload)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_confirm = QtWidgets.QPushButton(self.frame_5)
        self.pb_confirm.setStyleSheet("QPushButton:hover:pressed{\n"
                                      "    background-color: rgb(203, 203, 203);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    background-color: rgb(220, 220, 220);\n"
                                      "}\n"
                                      "QPushButton{\n"
                                      "    background-color: rgb(235, 235, 235);\n"
                                      "    padding: 5;\n"
                                      "    border-radius: 12;\n"
                                      "    border: 1px solid rgb(255, 170, 0);}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/Arrows/arrow-right-s-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_confirm.setIcon(icon1)
        self.pb_confirm.setIconSize(QtCore.QSize(16, 16))
        self.pb_confirm.setAutoRepeatDelay(300)
        self.pb_confirm.setObjectName("pb_confirm")
        self.gridLayout.addWidget(self.pb_confirm, 2, 1, 1, 1)
        self.pb_clear = QtWidgets.QPushButton(self.frame_5)
        self.pb_clear.setStyleSheet("QPushButton:hover:pressed{\n"
                                    "    background-color: rgb(203, 203, 203);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(220, 220, 220);\n"
                                    "}\n"
                                    "QPushButton{\n"
                                    "    background-color: rgb(235, 235, 235);\n"
                                    "    padding: 5;\n"
                                    "    border-radius: 12;\n"
                                    "    border: 1px solid rgb(86, 86, 86);}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/Design/eraser-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_clear.setIcon(icon2)
        self.pb_clear.setObjectName("pb_clear")
        self.gridLayout.addWidget(self.pb_clear, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setStyleSheet("border: None;\n"
                                   "border-radius:12;\n"
                                   "background-color: rgb(255, 170, 0);\n"
                                   "padding: 7;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout_3.addWidget(self.frame_3, 0, QtCore.Qt.AlignBottom)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_20.setText(_translate("Form", "Подразделение"))
        self.lbl_dep.setText(_translate("Form", "Подразделение"))
        self.lbl_sfl.setText(_translate("Form", "ФИО"))
        self.label_15.setText(_translate("Form", "Информация для пропуска"))
        self.label_16.setText(_translate("Form", "Срок действия заявки"))
        self.label_17.setText(_translate("Form", "C "))
        self.label_18.setText(_translate("Form", "По"))
        self.lbl_target.setText(_translate("Form", "Цель посещения"))
        self.lbl_last.setText(_translate("Form", "Отчество"))
        self.le_last.setPlaceholderText(_translate("Form", "Пример: Александрович"))
        self.le_email.setPlaceholderText(_translate("Form", "Пример: example@gmail.com"))
        self.lbl_sur.setText(_translate("Form", "Фамилия"))
        self.le_name.setPlaceholderText(_translate("Form", "Пример: Александр"))
        self.lbl_email.setText(_translate("Form", "E-mail"))
        self.le_phone.setPlaceholderText(_translate("Form", "Пример: +7 123 456 78 90"))
        self.le_sur.setPlaceholderText(_translate("Form", "Пример: Алексеев"))
        self.lbl_phone.setText(_translate("Form", "Телефон"))
        self.lbl_name.setText(_translate("Form", "Имя"))
        self.pb_photo.setText(_translate("Form", "Загрузить фото"))
        self.lbl_num.setText(_translate("Form", "Номер паспорта"))
        self.lbl_birth.setText(_translate("Form", "Дата рождения"))
        self.lbl_org.setText(_translate("Form", "Организация"))
        self.lineEdit_6.setPlaceholderText(_translate("Form", "Пример: какая-тоОрганизация"))
        self.le_num.setPlaceholderText(_translate("Form", "Пример: 123456"))
        self.le_series.setPlaceholderText(_translate("Form", "Пример: 1234"))
        self.lbl_prim.setText(_translate("Form", "Примечание"))
        self.lineEdit_7.setPlaceholderText(_translate("Form", "Пример: Хачу пиццы"))
        self.lbl_series.setText(_translate("Form", "Серия паспорта"))
        self.de_birth.setDisplayFormat(_translate("Form", "dd.MM.yyyy"))
        self.label_14.setText(_translate("Form", "Информация о посетителе"))
        self.label.setText(_translate("Form", "Прикрепляемые документы"))
        self.pb_upload.setText(_translate("Form", "Загрузить файл"))
        self.pb_confirm.setText(_translate("Form", "Подтвердить форму"))
        self.pb_clear.setText(_translate("Form", "Очистить форму"))
        self.label_2.setText(_translate("Form", "Подтверждение формы"))
